name: run-tests
run-name: Run tests / ${{ github.event.head_commit.message }}

on:
  pull_request:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:

  tests:
    name: test-${{ matrix.os.runs-on }} (${{ matrix.os.arch }})
    runs-on: ${{ matrix.os.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - runs-on: 'macos-latest'
            arch: 'arm64'
          - runs-on: 'ubuntu-24.04-arm'
            arch: 'arm64'
    steps:
      - uses: actions/checkout@v6
      - run: dotnet build -c Release
      - name: Run tests
        run: dotnet test -c Release --no-build --diagnostic --diagnostic-verbosity Trace

      # Upload Artifacts with Unique Name
      - name: Upload test results
        uses: actions/upload-artifact@v6
        if: always()
        with:
          name: test-${{ matrix.os.runs-on }}(${{ matrix.os.arch }})-trx-${{ github.run_id }}
          path: "**/log_*.diag"
